name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: download deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.36.4
      - name: check format
        run: deno fmt --check
      - name: lint
        run: deno lint
      - name: run tests
        run: deno test --allow-read --allow-write